- hosts: localhost
  tasks:
    - name: Install Packages
      become: yes
      package:
        name: "{{item}}"
        state: present
      with_items:
        - htop
        - tmux
        - git
